"""
Django settings for MovilSoft project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'ScannerApp',
    'rest_framework',
    'drf_spectacular',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

JAZZMIN_SETTINGS = {
    "custom_login_form": "ScannerApp.forms.CustomLoginForm",
    "site_title": "S.A Control",
    "site_header": "S.A Control",
    "site_brand": "S.A Control",
    "site_icon": "img/icono_scannerapp.png",
    "site_logo": "img/logo_scannerapp.png",
    "site_logo_classes": "img-circle",
    "welcome_sign": "Bienvenido a S.A Control Panel",
    "logged_out_message": "Has cerrado sesión correctamente.",
    "copyright": "S.A Control",
    "search_model": ["ScannerApp.Estudiantes", "ScannerApp.Ingreso"],

    #Tema Del Dashboard
    "theme": "darkly",
    "dark_mode": False,
    "dark_mode_theme": "darkly",

    #Aplicacion De CSS
    "custom_css": "custom/styles.css",

    #Navbar y Footer
    "navbar_small_text": True,
    "footer_fixed": True,
    "navbar_fixed": True,
    #Sidebar
    "show_sidebar": True,
    "navigation_expanded": True,
    #Iconos
    "icons":{

     "auth.user": "fas fa-user",
     "auth.group": "fas fa-users",
     "scannerapp.estudiantes": "fas fa-user-graduate",
     "scannerapp.ingreso": "fas fa-door-open",
    },
    
    #Menu
    "side_menu": [
        {"app": "ScannerApp", "label": "Estudiantes", "icon": "fas fa-user-graduate", "model": "ScannerApp.Estudiantes"},
        {"app": "ScannerApp", "label": "Ingreso", "icon": "fas fa-door-open", "model": "ScannerApp.Ingreso"},
    ],

    #Mostrar Configuracion Visual
    "show_ui_builder": True,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-warning",
    "accent": "accent-warning",
    "navbar": "navbar-warning navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": True,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-warning",
    "sidebar_nav_small_text": True,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": True,
    "sidebar_nav_flat_style": False,
    "theme": "solar",
    "dark_mode_theme": "cyborg",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-outline-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}


SPECTACULAR_SETTINGS = {
   'TITLE': 'ScannerApp API',
   'DESCRIPTION': """
ScannerApp es una aplicación institucional desarrollada para la Corporación Universitaria Minuto de Dios, cuyo objetivo principal es gestionar el control de ingreso de los estudiantes a espacios específicos dentro del campus universitario, como la Biblioteca y el Gimnasio.

El sistema registra de manera precisa cada entrada realizada por los estudiantes, permitiendo a los administradores llevar un monitoreo detallado del uso de estas instalaciones. Esta trazabilidad facilita la generación de reportes, el análisis de patrones de asistencia y la optimización de recursos en función del uso real de los espacios.

Además, ScannerApp ha sido diseñado con una interfaz moderna, intuitiva y segura, que se adapta a los flujos de trabajo institucionales y promueve una gestión eficiente y automatizada de los accesos. Su implementación fortalece la organización interna, mejora la experiencia del estudiante y contribuye al cumplimiento de las políticas de control y seguridad establecidas por la universidad.
""",
 'VERSION': '1.0.0',
    'CONTACT': {
        'name': 'Equipo de Desarrollo ScannerApp',
        'email': 'darwin.aveiga@uniminuto.edu.co',
        'url': 'https://www.scannerapp.edu.co/soporte',
    },
    'LICENSE': {
        'name': 'Licencia Institucional',
        'url': 'https://www.scannerapp.edu.co/licencia',
    },
    'TERMS_OF_SERVICE': 'https://www.scannerapp.edu.co/terminos',
    'EXTENSIONS_INFO': {
        'x-logo': {
            'url': '/static/img/logo_uniminuto.png',  # URL de tu logo
            'backgroundColor': 'transparent',
            'altText': 'ScannerApp Logo'
        }
    },
    'SCHEMA_PATH_PREFIX_TRIM': True,
    'SORT_OPERATIONS': True,
    'COMPONENT_SPLIT_REQUEST': True,
    'SERVE_INCLUDE_SCHEMA': False,
    'SERVE_SCHEMA': True,  # Usa el default
    'SWAGGER_UI_SETTINGS': {
        'docExpansion': 'none',  # contraído por defecto
        'deepLinking': True,
        'displayOperationId': True,
        'defaultModelExpandDepth': 2,
        'defaultModelsExpandDepth': 1,
        'defaultModelRendering': 'example',
        'showExtensions': True,
        'showCommonExtensions': True,
        'filter': True,  # permite filtrar endpoints
        'persistAuthorization': True,  # mantiene el token de autenticación después de refrescar
    },
    'REDOC_SETTINGS': {
    'hideDownloadButton': True,
    'expandResponses': "200,201",  # muestra respuestas exitosas
    'theme': {
        'logo': {
            'backgroundColor': 'transparent',  # Asegúrate de que se mantenga transparente
        }
    }
}

}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",  # dominio del backend
    "http://localhost:3000",  # dominio del frontend
    "https://tu-frontend.com",  # dominio en producción
]


ROOT_URLCONF = 'MovilSoft.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MovilSoft.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),  # default='localhost' es opcional
        'PORT': config('DB_PORT', default=3306, cast=int), 
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static",]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
