# Generated by Django 5.0.1 on 2025-04-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('idestudiante', models.AutoField(db_column='idEstudiante', primary_key=True, serialize=False)),
                ('id_programa', models.IntegerField(db_column='id_Programa')),
                ('nombres', models.CharField(db_column='Nombres', max_length=100)),
                ('edad', models.IntegerField(db_column='Edad')),
                ('codigo', models.CharField(db_column='Codigo', max_length=20)),
                ('correo', models.CharField(db_column='Correo', max_length=100)),
                ('semestre', models.IntegerField(db_column='Semestre')),
                ('contrasena', models.CharField(db_column='Contrasena', max_length=45)),
            ],
            options={
                'db_table': 'estudiantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('idingreso', models.AutoField(db_column='idIngreso', primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField(db_column='Fecha_Ingreso')),
                ('hora_ingreso', models.TimeField(db_column='Hora_Ingreso')),
            ],
            options={
                'db_table': 'ingreso',
                'managed': False,
            },
        ),
    ]
