# Generated by Django 5.0.1 on 2025-04-19 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScannerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiantes',
            options={'managed': False, 'verbose_name_plural': 'Estudiante'},
        ),
        migrations.AlterModelOptions(
            name='ingreso',
            options={'managed': False, 'verbose_name_plural': 'Ingreso'},
        ),
    ]
